spring.application.name=Ravon
server.port=32453
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.name=defaultDataSource
spring.datasource.url=jdbc:postgresql://localhost:5432/ravon?currentSchema=inver
spring.datasource.username=ravon
spring.datasource.password=11725110307
mybatis.mapper-locations=classpath:mapper/*.xml, classpath:mapper/*/*.xml
mybatis.type-aliases-package=tech.ravon.model
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.web.resources.static-locations=classpath:/static/, ${user.dir}/workspace/, ${user.dir}/src/main/resources/static/

mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

spring.servlet.multipart.max-file-size=512MB
spring.servlet.multipart.max-request-size=512MB

spring.web.resources.cache.period=0
spring.web.resources.cache.use-last-modified=true

spring.messages.basename=i18n/messages
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=false

collabora.url=http://localhost:9980
files.dir=./src/main/resources/static/doc/